# Generated by Django 4.1.5 on 2023-01-30 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_pub',
            new_name='date_posted',
        ),
    ]
